"""Generates the time-management logo: a clock face whose hands form a check mark.

Writes the three vector drawables (adaptive foreground, monochrome, splash logo) and the legacy
webp launcher icons for API 24/25 devices. Viewport is 128x128, centre (64,64).
"""
import math
import os
from PIL import Image, ImageDraw

RES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "app", "src", "main", "res")

RING = "#ffffff"          # white ring separates the face from the purple gradient behind it
FACE = "#ede9fe"          # faint lavender face
TICK = "#a855f7"          # purple_secondary_dark
HANDS = "#7c3aed"         # purple_primary_dark
PIVOT = "#e879f9"         # purple_accent

CX = CY = 64.0
R_RING = 56.0
R_FACE = 49.0
CHECK = [(48, 48), (64, 64), (92, 36)]   # short hand in from upper-left, long hand out to upper-right
HAND_W = 9.0
TICK_W = 3.0
PIVOT_R = 5.0


def circle_path(r):
    return f"M {CX:g} {CY - r:g} A {r:g} {r:g} 0 1 1 {CX:g} {CY + r:g} A {r:g} {r:g} 0 1 1 {CX:g} {CY - r:g} Z"


def ticks():
    out = []
    for h in range(12):
        a = math.radians(h * 30)
        major = h % 3 == 0
        r0 = 38.0 if major else 41.5
        r1 = 45.0
        x0, y0 = CX + r0 * math.sin(a), CY - r0 * math.cos(a)
        x1, y1 = CX + r1 * math.sin(a), CY - r1 * math.cos(a)
        out.append((x0, y0, x1, y1))
    return out


def tick_paths(color, indent):
    lines = []
    for x0, y0, x1, y1 in ticks():
        lines.append(
            f'{indent}<path android:pathData="M {x0:.2f} {y0:.2f} L {x1:.2f} {y1:.2f}" '
            f'android:strokeColor="{color}" android:strokeWidth="{TICK_W:g}" android:strokeLineCap="round"/>'
        )
    return "\n".join(lines)


def check_path(color, indent):
    d = " ".join(("M" if i == 0 else "L") + f" {x} {y}" for i, (x, y) in enumerate(CHECK))
    return (
        f'{indent}<path android:name="check_hands" android:pathData="{d}" android:strokeColor="{color}" '
        f'android:strokeWidth="{HAND_W:g}" android:strokeLineCap="round" android:strokeLineJoin="round"/>'
    )


def clock_group(indent, with_face=True):
    parts = []
    parts.append(f'{indent}<path android:name="ring" android:fillColor="{RING}" android:pathData="{circle_path(R_RING)}"/>')
    if with_face:
        parts.append(f'{indent}<path android:name="face" android:fillColor="{FACE}" android:pathData="{circle_path(R_FACE)}"/>')
    parts.append(tick_paths(TICK, indent))
    parts.append(check_path(HANDS, indent))
    parts.append(f'{indent}<path android:name="pivot" android:fillColor="{PIVOT}" android:pathData="{circle_path(PIVOT_R)}"/>')
    return "\n".join(parts)


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote", path)


HEADER = '<?xml version="1.0" encoding="utf-8"?>\n'

# 1. Adaptive-icon foreground: 108dp canvas, clock scaled to sit inside the 66dp safe zone.
foreground = HEADER + f'''<!-- The app icon: a clock whose hands make a check mark. Time, managed.
     Generated by tools/make_logo.py; the same geometry is in ic_inventoria_logo (splash)
     and ic_launcher_monochrome (themed icons). Scaled to 0.6 so the ring stays inside the
     adaptive icon's 66dp safe zone. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="128"
    android:viewportHeight="128">
    <group
        android:name="icon_group"
        android:pivotX="64"
        android:pivotY="64"
        android:scaleX="0.6"
        android:scaleY="0.6">
{clock_group("        ")}
    </group>
</vector>
'''
write(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), foreground)

# 2. Monochrome layer: Android tints the alpha, so this is the ring, ticks and hands only -- a
#    filled face would collapse the whole thing into one solid disc.
mono = HEADER + f'''<!-- Themed-icon (monochrome) layer. Only alpha matters here, so the face is left open: ring,
     ticks and the check hands read as a clock; a filled face would tint to a plain disc. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="128"
    android:viewportHeight="128">
    <group
        android:name="icon_group"
        android:pivotX="64"
        android:pivotY="64"
        android:scaleX="0.6"
        android:scaleY="0.6">
        <path android:name="ring" android:pathData="{circle_path(52.5)}" android:strokeColor="#ffffff" android:strokeWidth="7"/>
{tick_paths("#ffffff", "        ")}
{check_path("#ffffff", "        ")}
    </group>
</vector>
'''
write(os.path.join(RES, "drawable", "ic_launcher_monochrome.xml"), mono)

# 3. Splash logo: 120dp, sits inside SplashScreenContent's own translucent circle, so it is just
#    the clock at nearly full size.
logo = HEADER + f'''<!-- Splash / in-app logo: the same clock-and-check as the launcher icon, near full size. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="120dp"
    android:height="120dp"
    android:viewportWidth="128"
    android:viewportHeight="128">
    <group
        android:name="icon_group"
        android:pivotX="64"
        android:pivotY="64"
        android:scaleX="0.92"
        android:scaleY="0.92">
{clock_group("        ")}
    </group>
</vector>
'''
write(os.path.join(RES, "drawable", "ic_inventoria_logo.xml"), logo)


# 4. Legacy launcher webps (pre-API-26 devices and launchers that ignore adaptive icons).
def hex_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def gradient(size, c0, c1, c2):
    """135-degree three-stop gradient, matching ic_launcher_background / splash_background."""
    small = 128
    img = Image.new("RGB", (small, small))
    px = img.load()
    a, b, c = hex_rgb(c0), hex_rgb(c1), hex_rgb(c2)
    for y in range(small):
        for x in range(small):
            t = (x + y) / (2 * (small - 1))
            if t < 0.5:
                u = t / 0.5
                col = tuple(round(a[i] + (b[i] - a[i]) * u) for i in range(3))
            else:
                u = (t - 0.5) / 0.5
                col = tuple(round(b[i] + (c[i] - b[i]) * u) for i in range(3))
            px[x, y] = col
    return img.resize((size, size), Image.LANCZOS)


def draw_clock(draw, size, scale):
    """Draws the 128-unit clock geometry onto a size x size canvas at [scale] of the canvas."""
    k = size * scale / 128.0
    ox = oy = (size - 128 * k) / 2

    def P(x, y):
        return (ox + x * k, oy + y * k)

    def disc(cx, cy, r, fill):
        x, y = P(cx, cy)
        draw.ellipse([x - r * k, y - r * k, x + r * k, y + r * k], fill=fill)

    def seg(x0, y0, x1, y1, w, fill):
        draw.line([P(x0, y0), P(x1, y1)], fill=fill, width=max(1, round(w * k)))
        disc(x0, y0, w / 2, fill)
        disc(x1, y1, w / 2, fill)

    disc(CX, CY, R_RING, RING)
    disc(CX, CY, R_FACE, FACE)
    for x0, y0, x1, y1 in ticks():
        seg(x0, y0, x1, y1, TICK_W, TICK)
    for (x0, y0), (x1, y1) in zip(CHECK, CHECK[1:]):
        seg(x0, y0, x1, y1, HAND_W, HANDS)
    disc(CX, CY, PIVOT_R, PIVOT)


def legacy_icon(size, round_shape):
    ss = 4
    big = size * ss
    bg = gradient(big, "#8b5cf6", "#a855f7", "#c084fc").convert("RGBA")
    mask = Image.new("L", (big, big), 0)
    md = ImageDraw.Draw(mask)
    if round_shape:
        md.ellipse([0, 0, big - 1, big - 1], fill=255)
    else:
        # Legacy square icons carry their own padding: ~10% inset, ~18% corner radius.
        inset = round(big * 0.08)
        md.rounded_rectangle([inset, inset, big - 1 - inset, big - 1 - inset], radius=round(big * 0.18), fill=255)
    out = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    out.paste(bg, (0, 0), mask)
    draw = ImageDraw.Draw(out)
    draw_clock(draw, big, 0.66 if round_shape else 0.58)
    return out.resize((size, size), Image.LANCZOS)


for folder, size in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)):
    d = os.path.join(RES, f"mipmap-{folder}")
    legacy_icon(size, False).save(os.path.join(d, "ic_launcher.webp"), "WEBP", lossless=True)
    legacy_icon(size, True).save(os.path.join(d, "ic_launcher_round.webp"), "WEBP", lossless=True)
    print("wrote", d)

# Preview PNGs for eyeballing, written next to this script (gitignored: add tools/preview_*.png if not).
preview = legacy_icon(512, False)
preview.save(os.path.join(os.path.dirname(__file__), "preview_launcher.png"))
legacy_icon(512, True).save(os.path.join(os.path.dirname(__file__), "preview_round.png"))
print("done")
